apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: xdxct-kubevirt-device-plugin
  # namespace: "FILLED BY THE OPERATOR"
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - pods/eviction
  verbs:
  - get