apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xdxct-kubevirt-device-plugin
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - pods/eviction
  verbs:
  - get
