apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: xdxct-kubevirt-device-plugin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: xdxct-kubevirt-device-plugin
subjects:
- kind: ServiceAccount
  name: xdxct-kubevirt-device-plugin