# permissions for end users to edit gpuclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gpucluster-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-gpu-operator
    app.kubernetes.io/part-of: k8s-gpu-operator
    app.kubernetes.io/managed-by: kustomize
  name: gpucluster-editor-role
rules:
- apiGroups:
  - xdxct.com
  resources:
  - gpuclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - xdxct.com
  resources:
  - gpuclusters/status
  verbs:
  - get
