---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - xdxct.com
  resources:
  - gpuclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - xdxct.com
  resources:
  - gpuclusters/finalizers
  verbs:
  - update
- apiGroups:
  - xdxct.com
  resources:
  - gpuclusters/status
  verbs:
  - get
  - patch
  - update
