apiVersion: xdxct.com/v1alpha1
kind: GPUCluster
metadata:
  name: gpucluster-sample
spec:
  daemonSets: {}
  operator: {}
  devicePlugin:
    enabled: false
  kubevirtDevicePlugin:
    enabled: true
    repository: hub.xdxct.com/kubevirt 
    image: kubevirt-device-plugin
    version: devel
  vgpuDeviceManager:
    enabled: true
    repository: hub.xdxct.com/kubevirt 
    image: xdxct-vgpu-device-manager
    version: devel
    config:
      default: PANGU-A0-1G-1-CORE
