apiVersion: xdxct.com/v1alpha1
kind: GPUCluster
metadata:
  name: gpucluster-sample
spec:
  daemonSets: {}
  operator: {}
  devicePlugin:
    enabled: false
  kubevirtDevicePlugin:
    enabled: true
  

