apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: xdxct-device-plugin-ds
spec:
  selector:
    matchLabels:
      app: xdxct-device-plugin-ds
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: xdxct-device-plugin-ds
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: xdxct-device-plugin
      containers:
      - image: hub.xdxct.com/xdxct-docker/k8s-device-plugin:devel 
        name: xdxct-device-plugin
        securityContext:
          priviledged: true
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins