apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: xdxct-vfio-manager
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - pods/eviction
  verbs:
  - get
  - list
  - watch
  - update
  - delete
