apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xdxct-vfio-manager
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
  - update