apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: xdxct-vfio-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: xdxct-vfio-manager
subjects:
- kind: ServiceAccount
  name: xdxct-vfio-manager