apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: xdxct-vgpu-device-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: xdxct-vgpu-device-manager
subjects:
- kind: ServiceAccount
  name: xdxct-vgpu-device-manager
  namespace: default
  # namespace: "FILLED BY THE OPERATOR"
  # namespace: k8s-gpu-operator-system