apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: xdxct-vgpu-device-manager-ds
  # namespace: "FILLED BY THE OPERATOR"
  # namespace: default
  labels:
    app: xdxct-vgpu-device-manager-ds
spec:
  selector:
    matchLabels:
      app: xdxct-vgpu-device-manager-ds
  template:
    metadata:
      labels:
        app: xdxct-vgpu-device-manager-ds
    spec:
      serviceAccountName: xdxct-vgpu-device-manager
      containers:
      - name: xdxct-vgpu-device-manager
        image: "Filled By Configuration"
        imagePullPolicy: IfNotPresent
        env:
        - name: NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIGFILE
          value: "/configfile/config-vgpu.yaml"
        - name: DEFAULTVGPUCONFIG
          value: "Filled By Configuration"
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /sys
          name: container-sys
        - mountPath: /configfile
          name: configfile
      volumes:
      - name: configfile
        configMap:
          name: vgpu-device-config
      - name: container-sys
        hostPath:
          path: /sys
          type: Directory